### ISSUE TITLE
File extensions with hyphens are parsed incorrectly

### ISSUE THREAD

**Issue by benmccormick** [facebook/PathPicker#144]
When seeing file paths that have extensions including a hyphen fpp ignores the second half of the extension

![1__scratchworkspace___users_ben_code_windsor_wcui_dev_src_wcui__tmux__and_new_issue_ _facebook_pathpicker](https://cloud.githubusercontent.com/assets/1899941/7897862/468ea15e-06bb-11e5-8fad-33a9311dc4eb.png)

This is with fpp version 0.5.7.  I recognize that hyphenated extensions are an edge case, but matter for sublime text users looking through/editing configuration files.

This image also shows the spaces in filename issue from #145

**Comment by pcottle** [comment]
Yeah this is because grep services typically separate the filename from the results with either hyphens or colons depending on the context. heres an example:

```
> git grep -C 3 "__future__"
usageStrings.py:from __future__ import print_function
usageStrings.py-from screenFlags import ScreenFlags
usageStrings.py-
usageStrings.py-USAGE_INTRO = '''
```

if we just blindly allowed hyphens in our filename extensions, we would mismatch on `usageStrings.py-from` :*(

we have filesystem validation now but even with that, we need a heirarchy of the regex waterfall, and that leads to a tough situation -- we will **correctly** match on filename without the hyphen extension, and then with filesystem validation will invalidate this match

**Comment by pcottle** [comment]
so instead i need to loop through all regex results if filesystem validation is turned on and only return the first result that validates....

anyways #148 should address this, but it wasnt easy! haha
