### ISSUE TITLE
Using Old Result error

### ISSUE THREAD

**Issue by mrandrewandrade** [facebook/PathPicker#146]
I am using Linux mint and zsh

When I run fpp I get the following:

➜  ~  fpp
Using old result...
No lines matched!!

What does using old result mean?

**Comment by mrandrewandrade** [comment]
Actually I figured it out.  I just had to run:
fpp --clean

**Comment by mrandrewandrade** [comment]
Actaully nevermind.

When I run:

git status | fpp

It stops working again

**Comment by pcottle** [comment]
@mrandrewandrade can you attach a few things here for me to debug? try running the output of:

```
fpp --version;
ls -la ~/.fpp/;
git status;
```

note that if git status only outputs files that are deleted, youll have to add `-nfc` to skip file checks

**Comment by mrandrewandrade** [comment]
➜  ~  fpp           
Using old result...
No lines matched!!
➜  ~  fpp --version;
fpp version 0.6.0
➜  ~  ls -la ~/.fpp/;
total 56
drwxr-xr-x  2 anon anon  4096 May 30 12:44 .
drwx------ 49 anon anon 16384 May 31 17:48 ..
-rw-r--r--  1 anon anon   134 May 31 17:48 .fpp.log
-rw-r--r--  1 anon anon    26 May 31 17:48 .fpp.sh
-rw-r--r--  1 anon anon  1969 May 30 12:44 .pickle

**Comment by mrandrewandrade** [comment]
➜  cd /usr/local/bin/PathPicker/
➜  PathPicker git:(master) ls
assets  CONTRIBUTING.md  debian  fpp  fpp.rb  index.html  LICENSE  PATENTS  README.md  scripts  src
➜  PathPicker git:(master) fpp
Using old result...
No lines matched!!
➜  PathPicker git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
➜  PathPicker git:(master)

**Comment by pcottle** [comment]
```
➜ PathPicker git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
➜ PathPicker git:(master)
```

Ah yeah ok @mrandrewandrade I see what your problem is -- `git status` is listed as an example command to try out fpp but it will only work **if some files have been changed, so git status actually outputs a list of changed files**.

Running `fpp` on its own (with no previous result) won't do anything either, since it needs some input to show you the selector.

Here's the easiest way to just open up the program:

```
echo "foo/bar/banana.py" | fpp --no-file-checks
```

that will open up the UI and should work regardless oh where you are. to try out with some real input, try:

```
cd /usr/local/bin/PathPicker/;
git diff HEAD~10 --stat | fpp
```

that should allow you to open up the files.

Its also important to note that //fpp wont automatically use the stdout from the previous command//, so typing "ls" and then typing in fpp doesn't do anything (since fpp thinks it is getting no input).

Here the "old result" refers to the previous piped input to fpp. let me clarify this real quick

**Comment by mrandrewandrade** [comment]
Thanks!

**Comment by pcottle** [comment]
Sweet, I'm assuming the above worked :D hopefully the new error message makes this more clear!
