### ISSUE TITLE
From Chinese friends

### ISSUE THREAD

**Issue by kcbsbo** [facebook/PathPicker#158]
Hi guys,

I am in China, where you know that I cannot access the facebook.com at al, also cannot do the CLA test, That is annoying but I hope you know that still a large amount of people have this problem that cannot have stable access to your website, but we also want to give a contribute to your community.
Do you have any ideas?

kcbsbo,
Best regards

**Comment by pcottle** [comment]
Hey @kcbsbo thanks for dropping a line!

That is super annoying -- I'm sure other projects have run into this before, let me followup internally with our open source team since all we need is an electronic signature (it just happens to be hosted on facebook.com, but could be hosted anywhere). Stay tuned!

**Comment by pcottle** [comment]
Hey @kcbsbo, good news! We actually have a PDF version of the form that you can sign and email back, so we have a workaround :P bad news is that I'm having trouble tracking down the PDF version right now -- once it's monday here I can probably get a hold of it.

It's unfortunately a bit of a low-tech workaround (since I think you have to sign it manually and then scan it) but you only have to do the process once for all of our repos

**Comment by pcottle** [comment]
Hey @kcbsbo! I got a copy of the PDF -- can you email me at pcottle@fb.com? I can send it over.

Closing out in the meantime, thanks for your interest in the project though! :clap:
