### ISSUE TITLE
Can not handle files with spaces in their filenames. 0.6.1

### ISSUE THREAD

**Issue by chishui** [facebook/PathPicker#163]
Use "ls -la | fpp" in a directory and if the directory has files which names have spaces, fpp can not get the right file names. So these files are unselectable(as shown in the attached image
![0335e4d2-a790-497b-a919-285aa17f5f98](https://cloud.githubusercontent.com/assets/637584/8243401/9be1ec00-15cb-11e5-9933-ae0010ea5b61.png)
)

I checked the source code and found that in parse.py, only MASTER_REGEX_WITH_SPACES has the ability to parse filename like "a b c.txt". But this regex can only parse string with back slash like "/hello/world/a b c.txt". When I execute "ls", the only thing fpp can have is filename without any "/".

I think this can be solved in two ways:
1. change MASTER_REGEX_WITH_SPACES from "(([a-z.A-Z0-9\-_]|\s[a-zA-Z0-9\-_])+\/)+" to "(([a-z.A-Z0-9\-_]|\s[a-zA-Z0-9\-_])+\/)*"
2. call prependDir() before call matchLine()

**Comment by pcottle** [comment]
Yeah this is somewhat intentional for the REGEX_WITH_SPACES regex. otherwise we would parse almost **everything** in the stdin as a potential file and have to drop down to the filesystem to check if its a file or not. imagine if we were checking `xiuliyun` or `staff` or random bits of code in a `git diff` output

ill debug this though and see if we can selectively prepend a `./` and try to grab out the file. just worth mentioning it has performance considerations which is why we didnt just open up the flood gates from the getgo

**Comment by pcottle** [comment]
![screen shot 2015-06-19 at 4 33 56 pm](https://cloud.githubusercontent.com/assets/1135007/8264867/0501379c-16a1-11e5-9bc7-6481470692ca.png)

coming on up!
