### ISSUE TITLE
Alternative to fpp:  pe + fzf + $EDITOR

### ISSUE THREAD

**Issue by edi9999** [facebook/PathPicker#165]
Hi,

I just open-sourced a very small CLI because I liked the idea of fpp but didn't like that I was forced to use the default file picker (here's the issue where I asked how to do it : https://github.com/facebook/PathPicker/issues/69).

The CLI extracts filepaths from stdin, so that you can write:

git status | pe | fzf to select between files that are in your staged area for example (but it would work with any command of course).

Here's a link to my project : https://github.com/edi9999/path-extractor

Hope anyone will find it useful

**Comment by pcottle** [comment]
Very cool @edi9999 ! How do you end up doing the filepath extraction? it seems like you have pretty specific validators here:
https://github.com/edi9999/path-extractor/blob/master/validators.go

for instance, that wouldnt work with something like a retina image asset (`logo@2x.png`) right?

I do like the simplicity of the program though :D quite impressive.

closing this out since its not super actionable, but ill keep this in mind if someone files a similar issue

**Comment by edi9999** [comment]
They is one main regex that filters probable file paths. Those then get invalidated by some validators ( for example if the path is origin/master) it is probably not a file.

The goal is to return things that look like path names, eg return what a human would say are path names from a stream.

It doesn't use anything else than the content of the passed stream (eg doesn't use the file system to see if those files exist) . It also doesn't reformat the path names.

The strength is that it can be piped from/to anything
