### ISSUE TITLE
Adds '~/www' to the beginning of filenames, when used in an SVN repo

### ISSUE THREAD

**Issue by dpagano** [facebook/PathPicker#166]
When used in an SVN repo, and the selected files reside in a subfolder, fpp adds a '~/www' to the beginning of these files.

STR (Mac OS X):

1. svn stat | fpp
2. fpp recognizes 'subfolder/myfile.txt'
3. Select the file ('f')
4. Hit 'c' for command mode
5. fpp shows "Files you have selected: ~/www/subfolder/myfile.txt"

Instead, when doing the same from inside the subfolder, everything works as expected (fpp prepends './')

**Comment by pcottle** [comment]
@dpagano can you attach the output of `fpp --version`? I'm almost certain this was only an issue only with our older releases; we have since switched to falling back to relative paths rather than `~/www`. That functionality was vestigial / only applicable at Facebook where our sandbox is checked out at ~/www.

I'm not super familiar with SVN though -- do SVN commands give filepaths as relative from the root of the repo? If so we might need to add SVN repo logic -- you can see here:

https://github.com/facebook/PathPicker/blob/master/src/parse.py#L126

We try to get either the `hg root` or the git root, but we dont have any logic for svn. Do you feel brave enough to add it? :D

**Comment by dpagano** [comment]
@pcottle My bad, sorry.
brew insisted that I had the last version, but it was wrong (I had 0.5.5). I now installed 0.6.1 by hand and it works.
I think you can close this issue.

**Comment by pcottle** [comment]
Great! good to hear :+1:
