### ISSUE TITLE
unable to select long files

### ISSUE THREAD

**Issue by devisnik** [facebook/PathPicker#167]
I installed fpp 0.6.1 via homebrew. 
Long file paths are abbreviated, but are not selectable then.

![screen shot 2015-06-24 at 11 40 28](https://cloud.githubusercontent.com/assets/1219911/8327134/5b3b40e4-1a66-11e5-9806-92214a92881a.png)

**Comment by pcottle** [comment]
Do you mean the `.../` paths right? so this is actually an issue with git -- here is whats going on:

-- first, git status actually produces different output depending on if its going to be displayed on the screen vs piped into another program
-- when it gets piped, it decides to abbreviate the long paths with a preceding `.../` to designate that the actual path got truncated. so all information is lost by the time it gets to `fpp` :cry: 
-- since we added filesystem validation, these paths get filtered out since they dont look like files

You can actually skip filesystem validation with the `-nfc` option, in which then when you select them:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker/src/__tests__:master]$ echo ".../foo.py" | fpp -nfc

Warning! Some invalid or unresolvable files were detected.


It looks like one of these is a git abbreviated file with
a triple dot path (.../). Try to turn off git's abbreviation
with --numstat so we get actual paths (not abbreviated
versions which cannot be resolved.

Are you sure you want to continue? Ctrl-C to quit
```

we produce a big nasty warning. but unfortunately since they are filtered out, i guess its hard to get into that warning state

**Comment by pcottle** [comment]
@devisnik do you think it would be appropriate to warn when we get **any** of these files upon input? it would be a super jarring experience (well, super frictiony at least) but now that we have filesystem validation, its hard to understand why they arent selectable.

actually, let me instead change it so we "pretend" these are legit files so we allow you to select them

**Comment by pcottle** [comment]
All done! Next release won't have this issue :)

**Comment by devisnik** [comment]
Thank you, wasn't aware about that git issue. Works fine with `--numstat`.

I think it makes total sense to just fail when selecting one of them. 
Looking forward to the next release!
