### ISSUE TITLE
Files Nested in Multiple Directories Not Matched

### ISSUE THREAD

**Issue by groomsy** [facebook/PathPicker#176]
I've been trying to reproduce this in the test suite, but I have been unlucky thus far.

I've noticed that in some of my projects, if I make changes to files nested in multiple levels of a hierarchy that has directories with spaces in the names, no matches are found.

Example:
`Directory 1/Directory 2/test.txt`

This isn't normally an issue for me, but I am working on projects started and maintained by others and they have seeded this project with a similar directory structure, so it is not currently an option to rename the folder hierarchy to accommodate no spacing.

**Comment by pcottle** [comment]
> so it is not currently an option to rename the folder hierarchy to accommodate no spacing.

yeah understood. its tough to nail this down without a repro case -- can you report back with one and then we can add it to the test suite?

A lot of the spaces implementation was super incremental (since i didnt want to start overmatching on code results) so i wouldnt be surprised if there were some edge cases.

the files werent being deleted right? you need to pass the `-nfc` flag in that case

**Comment by pcottle** [comment]
(we have an internal bot that tracks open issues and docks points the longer they are open, so ima close this out till we have a repro -- but report back as soon as you have one!)
