### ISSUE TITLE
Is it possible to (1) copy file path to clipboard and (2) apply PathPicker feature to folder path too?

### ISSUE THREAD

**Issue by hajimezhao** [facebook/PathPicker#177]
Hi PathPicker author,
Is it possible to (1) copy file path to clipboard and (2) apply PathPicker feature to folder path too?

Best regards,
Khon

**Comment by pcottle** [comment]
Hey @hajimezhao ! We dont have support for directories yet, mainly because directories are such a disjunct set from filepaths for most unix commands. We'd have to provide a command API that would somehow provide different tokens (or different commands) for filenames versus directories and all of that.

Its not impossible to support, just requires a lot of work and careful consideration :P

For clipboard, yes you can! There are two things you might be interested in:

  * The first is the `pbcopy` command which copies to clipboard, so you can "paste". I think this command only comes on macs but is quite useful. you can pipe into copy like `echo "asd" | pbcopy`
  * The second is that we have a bit of hacky support for moving into the directory of a listed file. If you "cd" a file in FPP, we will actually copy it to a file in `~/.dircopy` (since we execute in subshells and you cannot change the outer shells directory instantly).

Then I have an alias to easily navigate to that directory:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker/src:master]$ type -a cdp
cdp is aliased to `cd "$(cat ~/.dircopy)"'
```

so my workflow is essentially `cd $F` >> program exits >> `cdp`

**Comment by pcottle** [comment]
Hope that helps!
