### ISSUE TITLE
support stream input

### ISSUE THREAD

**Issue by nuxdie** [facebook/PathPicker#184]
it would be nice to add support for input stream.
example, when I do grep in a large folder,
```
~/big-project/ grep -rl shop ./templates | fpp
```
it takes some time for grep to finish it's job. however I can see output while grep still searching.
fpp is waiting for grep to exit & only then it parses output.

another example is
```
~ tail -f filename_list.log | fpp
```
which is actually never finishes.

**Comment by pcottle** [comment]
Gah, It'd be awesome to support this one day but I don't really think it'd be possible anywhere in the nearterm :-/ the issue is that we parse the entire input before pickling it and loading up the UI:

https://github.com/facebook/PathPicker/blob/master/fpp#L27

You can always do something like `head -n 100` to grab bits of the input first and pipe to fpp, but theres no way we could support streaming without a giant refactor at the moment.

thanks for the input though!
