### ISSUE TITLE
Doesn't select 'deleted' items in git status output

### ISSUE THREAD

**Issue by banks** [facebook/PathPicker#189]
First off, fpp is an awesome tool I only came across recently. Great job!

Now I'm finding uses for it all the time... but I'm also finding pretty common cases where it appears not to work as I expect.

For example

```
$ git status
On branch foobar
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    foo/example/bar.xml

$ git status | fpp
No lines matched!!
```

Since README specifically claims git status support that surprises me. There are cases where I want to selectively "undelete" a bunch of files by `git checkout HEAD -- ...` and fpp would be awesome way to do that... except it apparently doesn't allow selection of deleted files.

It also appears not to allow selection of directories in git output which can also be annoying say if you want to `rm -rf ...` all of them.

I guess ultimately all of these things can be done some other way and you may have very good reasons for not allowing these selections that I've not considered. In which case feel free to close this, I just wanted to give feedback having found the tool so useful.

Thanks again

**Comment by pcottle** [comment]
Hey @banks ! I have good news for you :)

The reason why we don't detect deleted files is because we use //filesystem validation// on all of our matches (which is now on by default), so we can be a lot looser with our regexes and find all sorts of matches we otherwise wouldn't have been able to.

So if you want to select deleted files, just do `fpp -nfc` or `fpp --no-file-checks`.

Actually if you run `fpp --help`, your exact scenario is described as the reason why you might want to use that flag.

**Comment by pcottle** [comment]
For directories, we unfortunately don't support these for the time being for a few reasons:

  - Editor support for directories varies a bunch. Vim and sublime and all those classics handle it just fine, but stuff like `nano` just seems to print out a blank screen
  - Command mode gets a bit trickier with directories, especially if you have selected both files and directories. we would probably need to have two separate replacement tokens

However it's not impossible, just something we haven't thought through yet. I'll keep it on my radar since i do wish I could select directories sometimes (mainly for command mode)

**Comment by banks** [comment]
@pcottle thanks for the reply and shame on me for not Reading The Fantastic Manual...

Total aside: your use of //italics// looks like another phabricator user who often forgets the subtle differences between Markdown and Remarkup ;)

**Comment by pcottle** [comment]
lol yeah whoops, Facebook uses phabricator all day so its somewhat hardwired. glad i could help though!
