### ISSUE TITLE
On doing suspend vim gets killed with "Vim: Caught deadly signal HUP"

### ISSUE THREAD

**Issue by dfordivam** [facebook/PathPicker#194]
Every time I try to suspend the vim process opened using fpp, it gets killed.

$ git status | fpp
select files and do 'enter' to open files in vim
do ctrl-z to suspend the vim process
Vim: Caught deadly signal HUP                                                              
Vim: Finished.

System: Fedora, 3.19.7-200.fc21.x86_64
Let me know if more info is required

**Comment by pcottle** [comment]
Ahhhhh hrm this might be tricky @dfordivam since we launch the vim process within another shell script here:
https://github.com/facebook/PathPicker/blob/master/fpp#L50

its actually two levels deep since we generate the fpp.sh.

im not an expert in process suspension but i dont think we can support this easily, since im assuming processes launched from a shell script need to finish when the script exits.

what workflow are you trying to support? you can also run commands from within vim (small consolation i know)

**Comment by pcottle** [comment]
(closing out for now since i dont think this is technically possible to support, but curious to hear back)

**Comment by dfordivam** [comment]
I usually work on multiple projects/repos, so when I return back to work, I use 'git status' to fetch the files on which I need to work. Fpp turned out to be a useful tool to both see the status and open the files (hmmm... I know its called laziness).
But I do need to minimize the vim occasionally to do other stuff on terminal. I guess I will have to use fpp with this limitation then.

**Comment by pcottle** [comment]
Ahhhh yeah I see -- I usually just go with multiple tabs rather than suspending and resuming vim. interesting workflow though! sorry we couldn't help out, but sounds like you're getting some kind of use out of it

**Comment by pcottle** [comment]
Good news! We are adding a flag for this in #222
