### ISSUE TITLE
Sending editor to background gets stuck

### ISSUE THREAD

**Issue by Firehed** [facebook/PathPicker#206]
If you send your editor to the background (via `^z`) when it was opened by FPP, the whole thing gets stuck apparently waiting for a signal and won't end until you kill FPP via `kill` (`^c` is unresponsive), rather than returning to the shell as usual. So you get something like this:

    10:56:32 firehed@Erics-MacBook-Pro ~/some/path [0]$ grep -r www *|fpp
    (do things in vim, background with ctrl-z)
    3 files to edit
    ^C^C^C
    ^Z
    fg
    (`kill $FPP_PID` from another window)
    Vim: Caught deadly signal HUP
    Vim: Finished.

This is when using Vim on OS X in Bash, FPP v0.6.2 (installed via Homebrew). It didn't happen in the previous version I had installed; unfortunately, I have no idea what version that was (but it was something near the first public release).

**Comment by pcottle** [comment]
Yeah, this is unfortunately due to the fact that we launch the editor inside a subshell and attach it to tty directly. hence you cant simply suspend the editor process, since it belongs in that sub-shell process :(

I think there was a similar issue to this earlier -- theres no real way to solve this i dont think, especially with supporting both zsh and bash.

thanks for using FPP though! Lemme know if you have ideas (im not an expert on launching processes and separating them from the script being run, but also still blocking on them before exiting)

**Comment by pcottle** [comment]
Good news @Firehed  we are adding a flag for this in #222
