### ISSUE TITLE
Doesn't display output if root folder contains a space

### ISSUE THREAD

**Issue by mattfxyz** [facebook/PathPicker#219]
iOS project name contains a space and fpp does not display anything when I run `git status | fpp` after making a few changes.

**Comment by pcottle** [comment]
Can you attack the full input to fpp somewhere in a gist, and maybe your directory structure?

its expected we can catch spaces in names if they have a leading slash, but not if they are in the current directory (no leading slash)

**Comment by mattfxyz** [comment]
Here is a gist. https://gist.github.com/mattfxyz/60812914cf06aa193ad5

I had to recreate the issue (work project). 

an iOS project named "sample project" creates another folder called "sample project" for the source. The files inside that source folder are either not found or return the wrong path (I've seen both)

**Comment by pcottle** [comment]
Yeah, this is expected :( since the folder doesnt start with a leading slash, we can't recognize it. if we had to do all combinations of spaces + words before every input we'd quickly have a big performance problem.

if we had something like
`./Spaced Project/a.txt`

that would match it, but git outputs its paths in the way it chooses. sorry man!
