### ISSUE TITLE
Add functionality for executing keys when the list shows up

### ISSUE THREAD

**Issue by saveriomiroddi** [facebook/PathPicker#287]
A functionality that would be helpful for a use case of mine (and that could be useful in general, for `fpp` scripting) is to specify keys to execute when launching fpp.

Specifically, I use fpp with the content of the terminal, and I'd like to immediately move to the bottom of the list, where the relevant content is.

This could be accomplished simply by adding something along the lines of `--execute-keys END`.

What do you think? I actually have a [working version](https://github.com/facebook/PathPicker/compare/master...saveriomiroddi:sav-add_execute_keys), but I'd like to 1. know if this can be accepted, and if so, 2. to get more input before writing the UTs.

**Comment by pcottle** [comment]
For your specific case, would it be possible to simply just use `tac` to reverse the order of your input? then the program starts off with the top of the input selected (which is the relevant area you want).

I'm just wondering if we can keep PathPicker pretty inline with the unix functionality of "do one thing well" rather than add to our list of fairly obscure commands :P

Unit test coverage should be possible though, you could just add another argument to our master mapping of test cases. check `testScreen.py` which already provides pre-defined keys to the input and checks the output

**Comment by saveriomiroddi** [comment]
> For your specific case, would it be possible to simply just use tac to reverse the order of your input?

Not intuitively. I've found a way to make fpp get as input whatever in the terminal screen, without having to (re-)issue the command output piping to fpp. Turning the output upside down would make things look very weird (imagine a `git st` upside down, it works but it's strange).

Another way to look at this option is to have a counterpart to `record`. Right now there is a recording functionality, but not a playback; a concept like `playback-keys` may be it.

This functionality is strictly necessary, however, it makes this very intuitive.

**Comment by pcottle** [comment]
Yeah true. Ok I'm not crazy opposed to this given that the --record option exists. Would you like to try the implementation?

**Comment by saveriomiroddi** [comment]
Sure, the code is ready in the branch mentioned :smile: I've opened #288 for discussion.
