### ISSUE TITLE
Arbitrary command mode doesn't have aliases or shell functions

### ISSUE THREAD

**Issue by SeanA208** [facebook/PathPicker#32]
When executing a command in arbitrary command mode, fpp is unaware of any aliases or shell functions I may have defined in my .zshrc (I'm using zsh but I've tested this in bash as well). 

For example I have an alias `gco="git checkout"`and running `gco` in the arbitrary command mode gives:

```.fbPager.sh: line 4: gco: command not found```

**Comment by pcottle** [comment]
Yeah @SeanA208  we actually dont get any of the aliases that are already loaded in the shell script since we execute in another shell environment :*( So for bash we have to **manually** expand the aliases:

https://github.com/facebook/PathPicker/blob/master/src/output.py#L55

However no reason why we can't make a fallback...

**Comment by pcottle** [comment]
Alright this is a bit hacky but e0604190d46c03b61869607fc2cc1b725b72a800 should work. Can you try that? I don't have zsh installed unfortunately :-/

(obviously this isnt reflected in prod so youll have to make those changes manually to your brew installation)

thanks @SeanA208 for the report!
