### ISSUE TITLE
fpp fails when called from a symlink in Linux

### ISSUE THREAD

**Issue by lsmag** [facebook/PathPicker#33]
I'm creating an [Arch package](https://github.com/lsmag/pathpicker-git-arch) for PathPicker right now but I can't make a symlink to `fpp` work. This is the error I get:

    /home/lsmag/my-symlink-fpp: line 18: cd: /home/lsmag//home/lsmag/PathPicker: No such file or directory
    python2: can't open file '/src/processInput.py': [Errno 2] No such file or directory
    python2: can't open file '/src/choose.py': [Errno 2] No such file or directory
    :D

As you can see, the problem is `/home/lsmag//home/lsmag/PathPicker` = `/home/lsmag/` + `/home/lsmag/PathPicker`, which is the predictable output of both `dirname` and `readlink`.

Using `readlink -f`, however, the command runs just fine. This is how it is on my machine now:

    while [ -h "$WHEREAMI" ]; do
      WHEREAMI=$(readlink -f "$WHEREAMI")
    done

I don't know if it still works on Macs, though.

**Comment by bmwang** [comment]
you'll have to be a little bit careful - osx ships with posix readlink, and this script is written for osx. iirc, the posix readlink doesnt have the -f flag

on linux you'll be using gnu readlink, which is different and has the -f flag.

that's not the issue, thogh

it looks like readlink is giving you an absolute path when the script was written for a readlink that gives a relative path. this is probably because you symlinked fpp using an absolute path, which, imo, should be valid.

it wbn if the WHEREAMI resolution would respect symlinks created with absolute paths.

**Comment by pcottle** [comment]
@lsmag can you see if #16 fixes this for you?

**Comment by pcottle** [comment]
I think since we added the `  if [[ $SOURCE == /* ]]; then` in #16 then this will work for both relative and absolute symlinks -- so I'm going to call this closed! @lsmag can you try pulling down 16 and then trying?

**Comment by lsmag** [comment]
Yup, it worked, thanks =D

**Comment by lsmag** [comment]
I uploaded the package to [AUR](https://aur.archlinux.org/packages/pathpicker-git/), it can be installed using `yaourt`, `aura` or even downloading the package and calling `# pacman -U <path-to-pathpicker.tar.gz>`. Maybe change the README to add that?

**Comment by pcottle** [comment]
@lsmag what does `pacman` do besides unpack the tar? does it handle symlinking and sha checks and such?

**Comment by pcottle** [comment]
lets track this in #43

**Comment by lsmag** [comment]
@pcottle the package I built will download fpp from git, unpack on /opt and create a symlink on /usr/bin.
