### ISSUE TITLE
I have a directory that breaks fpp

### ISSUE THREAD

**Issue by jpeirce** [facebook/PathPicker#36]
`$ ls Music|fpp`
`Traceback (most recent call last):`
`  File "/home/jackson/src/PathPicker/src/choose.py", line 55, in <module>  `
`    curses.wrapper(doProgram)`
`  File "/usr/local/lib/python2.7/curses/wrapper.py", line 43, in wrapper`
`    return func(stdscr, *args, **kwds)`
`  File "/home/jackson/src/PathPicker/src/choose.py", line 26, in doProgram`
`    screen.control()`
`  File "/home/jackson/src/PathPicker/src/screenControl.py", line 266, in control`
`    self.moveCursor()`
`  File "/home/jackson/src/PathPicker/src/screenControl.py", line 498, in moveCursor`
`    self.stdscr.move(y, x)`
`_curses.error: wmove() returned ERR`

I put a pastebin of 'ls Music' here:
http://pastebin.ca/raw/2999325

I can't figure out what it's puking on though, I made another directory with some of the odd characters used and fpp handles that one fine...

**Comment by pcottle** [comment]
Wow I can repro! Let me try to debug this...

**Comment by pcottle** [comment]
Thanks for the file @jpeirce ! Just pushed a fix, will make it into the next release for sure.

This was happening because:
  * Your input had valid matches, but....
  * The matches were WAY down the list, more lines than the curses UI had available in the Y axis

So when the program started up with a scroll offset of 0, it crashed since it was trying to move the cursor to the first match (aka off the page). so just a quick update was needed before we move the cursor :tada: 

thanks a bunch! (note that it wont work with files that have spaces, so unfortunately most of our output will not match)
