### ISSUE TITLE
Linux packages

### ISSUE THREAD

**Issue by Daniel15** [facebook/PathPicker#43]
It would be good to have Linux packages available, at least .deb and .rpm versions. I don't know anyone that uses Linuxbrew, it doesn't seem ideal on Linux when better solutions exist.

The HHVM team distribute Linux packages, you could probably see how they do it.

**Comment by diwu1989** [comment]
+1
linuxbrew?! wat is that?! Make it work with `apt-get` please.

**Comment by gutenye** [comment]
For ArchLinux, Install it by `$ pacaur -S fpp`

**Comment by jainpranav** [comment]
+1

**Comment by pcottle** [comment]
Yeah this would be sweet, ill have to ask around internally since i have no idea how to build / release a linux package. @Daniel15 let me know if you have any names in mind for people we can bug :)

**Comment by Daniel15** [comment]
I have no idea either :D I think @ptarjan and @jwatzman maintain the HHVM packaging scripts so they might know how to get started with this.

**Comment by jwatzman** [comment]
https://github.com/hhvm/packaging/blob/master/hhvm/deb/package is how HHVM does it -- that runs on a cronjob on a VM on a Mac Pro under someone's desk :-P Someone was in the process of writing a proper Debian package, which might be the way to go -- AIUI it isn't actually that hard, and has a lot better tooling than some random shell script, Debian is actually quite good at that sort of thing. As for the actual builds, last I heard the sandcastle/Fog team(s) were working on getting Debian VMs on Sandcastle so we can do our CI/builds that way; I got access to a couple VMs but never really got it set up, and haven't heard anything more about the actual infra and CI stuff there.

Feel free to grab me in the office if you want to chat; sometime May 25 or after would be best unless this is urgent, I'm working on the HHVM lockdown right now.

**Comment by jwatzman** [comment]
But you're going to have a *much* easier time since it looks like this is just pure python, right? Most of the HHVM complexity has to do with supporting finding several third-party libraries (or building new enough versions of them if the distro's is too old) for C++ compilation, and then generalizing that over a bunch of different supported versions of Debian and Ubuntu.

**Comment by lsmag** [comment]
There's also (fpp-git)[https://aur.archlinux.org/packages/fpp-git/] in AUR which installs PathPicker directly from github's master.

Also, maybe it's better not to point *pacaur* as the package manager? I use *aurapm*, for example.

**Comment by pcottle** [comment]
Oh thanks for the tip @lsmag . I'd be fine with pointing towards `fpp-git` in AUR since we won't have to worry about updating the release (downside is that it'll run a less stable version of the code, aka master)

Anyone have any objections to pointing to `fpp-git`? Or should we do that + `pacaur`?

Also thanks @jwatzman for the comment! Will ping you if we don't get any community contributions that work. I do agree that this is much easier than building hhvm releases

**Comment by Daniel15** [comment]
We should still make .deb and .rpm packages for distros that use those.

**Comment by lsmag** [comment]
I believe most Arch users know how to install an AUR package, so I don't believe favouring a certain package manager is good (and there are [many](https://wiki.archlinux.org/index.php/AUR_helpers#AUR_search.2Fbuild_helpers) )

**Comment by Daniel15** [comment]
Yes, Debian users don't use AUR packages though. Not everyone uses Arch :)

**Comment by lsmag** [comment]
Yep @Daniel15 , I was only answering @pcottle 's question regarding `AUR` or `AUR+pacaur` ;)

**Comment by Daniel15** [comment]
Oh right :+1:

**Comment by pcottle** [comment]
Alright now we are at least pointing to `fpp-git`, and non-Arch peeps can install manually. Closing out since I don't think maintaining our own distribution packages is going to be super sustainable (at least until we get some internal volunteers).

If anyone wants to attach the command line inputs to pull down / install that package, shoot em over! I can at least inline those instructions

**Comment by pcottle** [comment]
@lsmag lemme know if you have the above^^

**Comment by lsmag** [comment]
You can point to the [Arch wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages), it has a link for the [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers#AUR_search.2Fbuild_helpers)

**Comment by Daniel15** [comment]
@pcottle  - Can we keep this task open for tracking purposes, until we have .rpm and .deb packages? Most likely someone will open an identical task when they notice a lack of packages, so we should still keep this open to track that.

**Comment by pcottle** [comment]
sure @Daniel15 -- hope people notice the "help wanted" label in bold

**Comment by pallavagarwal07** [comment]
I am a student of IIT Kanpur with a lot of free time and multiple testing platforms (Debian, Arch, Fedora). Is there anything I can do to help?

**Comment by pcottle** [comment]
Sure @pallavagarwal07  -- could you try whipping up a list of the install commands for the different package managers that use the package we link to above? and make sure it works on debian / arch / fedora

For instance, we have the homebrew install command as :
`brew update; brew install fpp; fpp`

It'd be nice if we could point to something similar like:
```
pacaur -S fpp; fpp # for pacaur
arch apt-get fpp; fpp # for whatever works for arch
```

**Comment by pallavagarwal07** [comment]
@pcottle OK, I'll get right on it.

**Comment by pallavagarwal07** [comment]
@pcottle 
I think the best way of distributing it to debian platforms would be with a .deb package. It installs instantly and since the project is pure python, the .deb package is extremely easy to create.

Here is the one I created using current master branch : 
https://drive.google.com/file/d/0B6jsnt965ZwraVk1bEo2VmpXd1U/view?usp=sharing
It *should* install on any debian based OS.

**Comment by pcottle** [comment]
My only worry about Debian packages is that our team wouldn't know how to build / update / maintain them. Could you add to the scripts/makeDist.sh with the commands necessary? That way we can update it along with homebrew and keep everyone up to date

**Comment by pallavagarwal07** [comment]
I'll update the scripts as soon as I generalize the package (extracting necessary details from the package itself) 
Could you tell me the Name and email of the person whose info is to be written in packaging control file (Maintainer: is a necessary field)

**Comment by pcottle** [comment]
Yeah sure @pallavagarwal07 --

1) Owner name: `Peter Cottle`
2) Owner email: `pcottle@fb.com`

**Comment by pallavagarwal07** [comment]
@pcottle
Debian packages also require (or rather recommend) a man page for every executable (in this case fpp). Is there one? Or should I skip the man page in the packaging?

**Comment by pcottle** [comment]
Hrm, the output of `fpp --help` is basically what I would describe as our man page. could we use that automatically somehow? maybe do it as part of the script?

**Comment by pallavagarwal07** [comment]
@pcottle
I think man pages are supposed to follow a very strict format. Scripting to use the same at both places wouldn't be hard at all if the existing is modified to fit the criteria (should I do it?) 
For now, I have done it without the man page (help command obviously still works) and opened a pull request. Have you seen it?

**Comment by pcottle** [comment]
> I think man pages are supposed to follow a very strict format.

ah well in that case, lets not bother. we can move this discussion to the PR!
