### ISSUE TITLE
Publish installable package on PyPI

### ISSUE THREAD

**Issue by ionelmc** [facebook/PathPicker#56]

**Comment by Eyjafjallajokull** [comment]
+1

**Comment by sametmax** [comment]
+1 You can provide the bash script as an asset if you want, but it's probably easier to just make a setuptool entrypoint calling a function Python. If you need guidance for this, ping me.

**Comment by pcottle** [comment]
Unfortunately now that we're a homebrew recipe, we can't submit to PyPI:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md

Also I'm hesitant to switch to PyPI since we might want to use other languages some day (curses UI written in react? yes pleaseeee), but thanks for your interest in the project!
