### ISSUE TITLE
Fails when relative path is not prepended with "./"

### ISSUE THREAD

**Issue by mkell85** [facebook/PathPicker#63]
Doesn't play well with ack (or any other tool with similar output) because ack does not prepend a "./" to the file list returned from . E.g.

> ack -l 'foo'
junk/foo/bar.txt

> ack -l 'foo' | fpp   <------- Does not work needs ./junk/foo/bar.txt instead.

**Comment by pedrox** [comment]
Describe what do not work.

**Comment by gsheld** [comment]
+ 1

**Comment by brentvatne** [comment]
Same problem here, on a React Native project I ran:

`ag RCTNavItem node_modules | fpp`

I then scrolled down to `node_modules/react-native/React/Views/RCTNavItem.h:12:@interface RCTNavItem : UIView` and pressed enter

It opened:
`~/www/node_modules/react-native/React/Views/RCTNavItem.h `

I wanted it to open the relative path:
`./node_modules/react-native/React/Views/RCTNavItem.h`

**Comment by dutzi** [comment]
+1 for command line svn

**Comment by brentvatne** [comment]
To anyone else having the issue I mentioned above with `ag`, for now it works fine to do `ag searchterm path --ackmate | fpp`

**Comment by pcottle** [comment]
Sorry for the `~/www` fallback, that is vestigial and only relevant for facebook dev environments.

we only do a hail-mary fallback punt if you are working outside of a git or mercurial repo, since we parse the top-level path here:
https://github.com/facebook/PathPicker/blob/master/src/parse.py#L38-L69

so this shouldn't be superrrrr common, but i guess it's clearly happening.

Anyways this is resolved by e302f16118e0a9bbd38b202e1d892a68b30f227c, update your version manually or wait for the next release to fix this! thanks all for the report

**Comment by brentvatne** [comment]
great, thanks @pcottle!
