### ISSUE TITLE
Add common next/prev line keys

### ISSUE THREAD

**Issue by mstorus** [facebook/PathPicker#65]
A proposal to add the common Mac/Unix/Emacs `ctrl + n` and `ctrl + p` commands to go to next or previous line.

![tungsten python 201x50-1](https://cloud.githubusercontent.com/assets/1182738/7547053/96565dc6-f59a-11e4-9722-2112f0454e56.jpg)

From http://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts
![table of keyboard shortcuts - wikipedia the free encyclopedia](https://cloud.githubusercontent.com/assets/1182738/7546998/d0779e44-f599-11e4-9a94-ed38455e2464.jpg)

**Comment by pcottle** [comment]
From looking around the web, it looks like curses cant determine if modifier keys are set:
http://stackoverflow.com/questions/4684739/how-to-get-shiftx-altx-keys-in-curses/9775675#9775675
http://stackoverflow.com/questions/9061111/ncurses-with-arrow-keys-plus-modifiers

Since they aren't event sent to the terminal :-/ otherwise id love to add this and add other support for all sorts of modifiers

(seems there is some third party library that attempts to do this but im hesitant to pull it in)

**Comment by pcottle** [comment]
(wish we had a `cantfix` label, was looking for that one)

**Comment by mstorus** [comment]
Would it be sufficient to listen for the `Shift Out` and `Data Link Escape` control codes?
Even if you can't tell if a modifier key was set, pressing `Ctrl-n` and `Ctrl-p` seem to produce those control codes, respectively.

I'm not very familiar with curses, so I don't know how portable this solution is.

**Comment by pcottle** [comment]
yeah i dont think its an issue with what the control codes are, but rather the fact that the terminal / curses doesnt receive them at all. only exceptions are situations like `tmux` which gets all the keypresses, but then tmux doesnt pipe them into the running terminal :P

if you can get a working version in curses then id be down to implement (and we should update all those stack overflow answers haha) but keeping this closed for now
