### ISSUE TITLE
Unicode Handling

### ISSUE THREAD

**Issue by BillLeecn** [facebook/PathPicker#78]
Unicode character is not displayed correctly, and unicode filename cannot be recognized, either.

To reproduce:
```
git init .
mkdir test
touch test/test
touch test/简体中文
git add test
git config core.quotepath false
```

## Case 1
Expected output of `LANG=C git status | fpp`:
```
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   test/test
	new file:   test/简体中文
```
Actural output:
```
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

    new file:   test/test
    new file:   test/��~@��~S中�~V~G
```

The 2nd "new file" cannot be selected.

## Case 2
Actural output of `LANG=zh_CN.UTF-8 git status | fpp`
```��~M��~N�~H~F�~T� master

�~H~]��~K�~O~P交

��~A�~O~P交�~Z~D�~O~X�~[���~Z
  ��~H使�~T� "git rm --cached <file>..." �~R��~G��~Z~B��~X�~L���~I

    �~V��~V~G件:    test/test
    �~V��~V~G件:        test/��~@��~S中�~V~G

```

**Comment by pcottle** [comment]
yeahhhhh woof there are probably a few things we'll need to do here:

 * the first is the most basic -- parse the incoming stdin as utf8 aware and be able to display it correctly
 * the second however is the more complex -- regex match **against** utf8 as well, meaning our regexes need to be updated.

The latter has me worried the most :see_no_evil: maybe @cosbynator can help us since he's mr utf8 regex:
http://instagram-engineering.tumblr.com/post/118304328152/emojineering-part-2-implementing-hashtag-emoji

**Comment by zkanda** [comment]
Woot! The latter seems scary to implement. :hankey:

**Comment by BillLeecn** [comment]
Cosbynator's regex is used to match emoji, but more characters should be matched to handle unicode filenames. For East Asians, *CJK Unified Ideographs* is important. It consists of serveral unicode ranges:
* CJK Unified Ideographs: 4E00 to 9FFF
* CJK Unified Ideographs Extension A: 3400 to 4DBF
* CJK Unified Ideographs Extension B: 20000 to 2A6DF
* CJK Unified Ideographs Extension C: 2A700 to 2B73F
* CJK Unified Ideographs Extension D: 2B740 to 2B81F

As a Simplified Chinese users, I think (at least) 4E00 to 9FFF and 3400 to 4DBF should be matched.

**Comment by pcottle** [comment]
Closing this out since I don't think we'll be able to support in anytime soon (and I keep getting nagged by the reap bot), but once almost everyone is on python3 I can add it!
