### ISSUE TITLE
For path with ".." in front of it, the path picker does not recognize it as part of the path. 

### ISSUE THREAD

**Issue by shunjili** [facebook/PathPicker#85]
![screenshot 2015-05-11 15 13 45](https://cloud.githubusercontent.com/assets/1924751/7576229/5b6f4094-f7f0-11e4-9680-84f15c360699.png)

**Comment by pcottle** [comment]
I can't repro this -- I think it is solved by #31. @shunjili  can you try manually installing (instructions in readme) and trying to repro?

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ echo "../homebrew/README.md" | fpp
executing command:
cat '../homebrew/README.md' | wc -l
      42
```
![screen shot 2015-05-11 at 3 29 14 pm](https://cloud.githubusercontent.com/assets/1135007/7576464/9bcc7fba-f7f2-11e4-9988-c0e1944d20c2.png)

closing out for now since i think this is fixed
